# Generated by Django 3.2.9 on 2021-11-09 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NA', 'Outro/Não declarado')], default='NA', max_length=20)),
                ('phoneNumber', models.IntegerField(default=0)),
                ('address1', models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 1')),
                ('address2', models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 2')),
                ('cep', models.CharField(default='NA', max_length=8)),
                ('city', models.CharField(default='NA', max_length=105)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('globaluser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.globaluser')),
            ],
            bases=('users.globaluser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('globaluser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.globaluser')),
                ('registrationNumber', models.IntegerField(default=0)),
                ('Pontos', models.IntegerField(default=0)),
            ],
            bases=('users.globaluser',),
        ),
    ]
