# Generated by Django 3.2.8 on 2021-10-20 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprestas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(default='NA', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível'), ('M', 'Em Manutenção'), ('A', 'Atrasado')], default='D', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='globaluser',
            name='cep',
            field=models.CharField(default='NA', max_length=8),
        ),
        migrations.AlterField(
            model_name='globaluser',
            name='cpf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='globaluser',
            name='phoneNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='registrationNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emprestas.item')),
                ('author', models.CharField(max_length=50)),
                ('language', models.CharField(default='Português', max_length=20)),
            ],
            bases=('emprestas.item',),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emprestas.item')),
            ],
            bases=('emprestas.item',),
        ),
        migrations.CreateModel(
            name='DigitalMedia',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emprestas.item')),
            ],
            bases=('emprestas.item',),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emprestas.item')),
            ],
            bases=('emprestas.item',),
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emprestas.item')),
            ],
            bases=('emprestas.item',),
        ),
        migrations.CreateModel(
            name='AcademicWork',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emprestas.book')),
            ],
            bases=('emprestas.book',),
        ),
    ]
