# Generated by Django 3.2.6 on 2021-10-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestas', '0002_auto_20211019_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaluser',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=255),
        ),
        migrations.AlterField(
            model_name='globaluser',
            name='phoneNumber',
            field=models.CharField(default='(00) 00000-0000', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='registrationNumber',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
