# Generated by Django 3.2.6 on 2021-10-27 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emprestas', '0003_auto_20211026_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('globaluser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emprestas.globaluser')),
                ('collaboratorRegistrationNumber', models.CharField(default='00000000', max_length=8)),
            ],
            bases=('emprestas.globaluser',),
        ),
        migrations.RenameField(
            model_name='student',
            old_name='registrationNumber',
            new_name='studentRegistrationNumber',
        ),
        migrations.AddField(
            model_name='professor',
            name='professorRegistrationNumber',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='globaluser',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=20),
        ),
        migrations.CreateModel(
            name='UnidadeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(default='00.000.000/0000-00', max_length=20)),
                ('phoneNumber', models.CharField(default='(00) 00000-0000', max_length=255)),
                ('address1', models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 1')),
                ('address2', models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 2')),
                ('cep', models.CharField(default='NA', max_length=8)),
                ('city', models.CharField(default='NA', max_length=105)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
