# Generated by Django 3.2.6 on 2021-11-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestas', '0005_rename_unidadeuser_unityuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
