# Generated by Django 3.2.8 on 2021-11-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='quantity',
            new_name='availableQuantity',
        ),
        migrations.AddField(
            model_name='books',
            name='totalQuantity',
            field=models.IntegerField(default=0),
        ),
    ]
