# Generated by Django 3.2.8 on 2021-11-20 00:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_date', models.DateField()),
                ('return_date', models.DateField()),
                ('loan_status', models.CharField(max_length=10)),
                ('loan_user', models.CharField(max_length=100)),
            ],
        ),
    ]
