# Generated by Django 3.2.8 on 2021-11-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='loan_status',
            field=models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível'), ('M', 'Em Manutenção'), ('A', 'Atrasado')], default='I', max_length=1),
        ),
    ]
