# Generated by Django 3.2.8 on 2021-11-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loans_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='loan_items',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_status',
            field=models.CharField(choices=[('E', 'Encerrado'), ('C', 'Pendente'), ('A', 'Atrasado')], default='I', max_length=1),
        ),
    ]
