# Generated by Django 3.2.8 on 2021-11-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20211120_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='loan_date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_items',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='loans',
            name='return_date',
            field=models.DateField(editable=False),
        ),
    ]
