# Generated by Django 3.2.8 on 2021-11-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20211122_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='loan_date',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='return_date',
        ),
    ]
