# Generated by Django 3.2.6 on 2021-10-11 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Danos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível'), ('M', 'Em Manutenção'), ('A', 'Atrasado')], default='D', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('language', models.CharField(default='Português', max_length=20)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível'), ('M', 'Em Manutenção'), ('A', 'Atrasado')], default='D', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MidiaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível'), ('M', 'Em Manutenção'), ('A', 'Atrasado')], default='D', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível'), ('M', 'Em Manutenção'), ('A', 'Atrasado')], default='D', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Periferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível'), ('M', 'Em Manutenção'), ('A', 'Atrasado')], default='D', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Previsão',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TrabalhoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível'), ('M', 'Em Manutenção'), ('A', 'Atrasado')], default='D', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(default='0', max_length=14)),
                ('telefone', models.CharField(default=0, max_length=11)),
                ('address1', models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 1')),
                ('address2', models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 2')),
                ('cep', models.CharField(default='NA', max_length=9, verbose_name='CEP')),
                ('city', models.CharField(default='NA', max_length=105)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(default='0', max_length=11)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NA', 'Outro/Não declarado')], default='NA', max_length=20)),
                ('telefone', models.CharField(default=0, max_length=11)),
                ('address1', models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 1')),
                ('address2', models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 2')),
                ('cep', models.CharField(default='NA', max_length=9, verbose_name='CEP')),
                ('city', models.CharField(default='NA', max_length=105)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(default='0', max_length=11)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NA', 'Outro/Não declarado')], default='NA', max_length=20)),
                ('telefone', models.CharField(default=0, max_length=11)),
                ('address1', models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 1')),
                ('address2', models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 2')),
                ('cep', models.CharField(default='NA', max_length=9, verbose_name='CEP')),
                ('city', models.CharField(default='NA', max_length=105)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=8, verbose_name='Número de Matrícula')),
                ('cpf', models.CharField(default='0', max_length=11)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NA', 'Outro/Não declarado')], default='NA', max_length=20)),
                ('telefone', models.CharField(default=0, max_length=11)),
                ('address1', models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 1')),
                ('address2', models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 2')),
                ('cep', models.CharField(default='NA', max_length=9, verbose_name='CEP')),
                ('city', models.CharField(default='NA', max_length=105)),
                ('Pontos', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
