# Generated by Django 3.2.6 on 2021-10-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MidiaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Periferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TrabalhoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='address1',
            field=models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 1'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='address2',
            field=models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 2'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.CharField(default='NA', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='city',
            field=models.CharField(default='NA', max_length=105),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default='0', max_length=11),
        ),
        migrations.AddField(
            model_name='aluno',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NA', 'Outro/Não declarado')], default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='address1',
            field=models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 1'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='address2',
            field=models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 2'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cep',
            field=models.CharField(default='NA', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='city',
            field=models.CharField(default='NA', max_length=105),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(default='0', max_length=11),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NA', 'Outro/Não declarado')], default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='professor',
            name='address1',
            field=models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 1'),
        ),
        migrations.AddField(
            model_name='professor',
            name='address2',
            field=models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 2'),
        ),
        migrations.AddField(
            model_name='professor',
            name='cep',
            field=models.CharField(default='NA', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='professor',
            name='city',
            field=models.CharField(default='NA', max_length=105),
        ),
        migrations.AddField(
            model_name='professor',
            name='cpf',
            field=models.CharField(default='0', max_length=11),
        ),
        migrations.AddField(
            model_name='professor',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NA', 'Outro/Não declarado')], default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='unidade',
            name='address1',
            field=models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 1'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='address2',
            field=models.CharField(default='NA', max_length=255, verbose_name='Endereço, linha 2'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='cep',
            field=models.CharField(default='NA', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='city',
            field=models.CharField(default='NA', max_length=105),
        ),
        migrations.AddField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(default='0', max_length=14),
        ),
        migrations.AddField(
            model_name='unidade',
            name='telefone',
            field=models.CharField(default=0, max_length=11),
        ),
    ]
