# Generated by Django 3.2.9 on 2021-11-09 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(default='NA', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível'), ('M', 'Em Manutenção'), ('A', 'Atrasado')], default='D', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.item')),
                ('author', models.CharField(max_length=50)),
                ('language', models.CharField(default='Português', max_length=20)),
            ],
            bases=('products.item',),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.item')),
            ],
            bases=('products.item',),
        ),
        migrations.CreateModel(
            name='DigitalMedia',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.item')),
            ],
            bases=('products.item',),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.item')),
            ],
            bases=('products.item',),
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.item')),
            ],
            bases=('products.item',),
        ),
        migrations.CreateModel(
            name='AcademicWork',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.book')),
            ],
            bases=('products.book',),
        ),
    ]
